package com.pottda.game.model;

import com.pottda.game.Util;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by rikar on 2017-04-07.
 */

public abstract class Item extends ProjectileListenerAdapter {
    /**
     * An AttackItem is a starting point and cannot be chained into
     */
    protected boolean isAttackItem;
    /**
     * A SecondaryAttackItem "stops" the chain, as items beyond it are linked to that item instead
     */
    protected boolean isSecondaryAttackItem;
    /**
     * A ProjectileModifier modifies projectiles and needs to be attached as a ProjectileListener
     */
    protected boolean isProjectileModifier;
    /**
     * List of points relative to origin 0,0 of the item's positions
     */
    protected List<int[]> basePositions;
    /**
     * List of points where the item will look for its output paths
     * (Generally only one)
     */
    protected List<int[]> baseOutputs;
    /**
     * A List to the items output items, generated by the Inventory when it compiles
     */
    protected List<Item> outputItems;

    /**
     * Direction of the item in terms of number pi/2 rotations
     */
    public int orientation;
    /**
     * X-orientation within its inventory
     */
    public int x;
    /**
     * Y-orientation within its inventory
     */
    public int y;

    /**
     * Pseudo-constructor, called if instantiated without constructor (probably really bad practice)
     */
    public void init() {
        basePositions = new ArrayList<int[]>();
        // Set default properties
        isAttackItem = false;
        isProjectileModifier = false;
        isSecondaryAttackItem = false;

        // Set properties based on dynamic type
        initDynamic();
    }

    /**
     * Is called at the end of init(), meaning it overrides the
     * default properties if wanted
     */
    protected abstract void initDynamic();

    /**
     * Returns a list of {@code Integer}, where each corresponds to a space where this item is.
     * <p>
     * The function sequences a coordinate grid with width {@code w} into a single number so
     * that i.e. (1,2) with w = 5 is equivalent to 1 + (2*5) = 11
     *
     * @param w the width of the grid
     * @return a {@code List<Integer>}
     */
    public List<Integer> getPositionsAsIntegers(int w) {
        List<Integer> list = new ArrayList<Integer>();

        for (int[] p : basePositions) {
            int[] rotatedPoint = Util.rotate(p[0], p[1], orientation);
            int v = (rotatedPoint[0] + x) +    // Add x to convert to absolute coordinate in Inventory
                    (rotatedPoint[1] + y) * w;     // Multiply to add the whole number of rows
            list.add(v);
        }

        return list;
    }

    /**
     * Returns a list of {@code Integer}, where each corresponds to a space where the item's
     * output is.
     * <p>
     * The function sequences a coordinate grid with width {@code w} into a single number so
     * that i.e. (1,2) with w = 5 is equivalent to 1 + (2*5) = 11
     *
     * @param w the width of the grid
     * @return a {@code List<Integer>}
     */
    public List<Integer> getOutputAsInteger(int w) {
        List<Integer> list = new ArrayList<Integer>();

        for (int[] p : baseOutputs) {
            int[] rotatedPoint = Util.rotate(p[0], p[1], orientation);
            int v = (rotatedPoint[0] + x) +    // Add x to convert to absolute coordinate in Inventory
                    (rotatedPoint[1] + y) * w;     // Multiply to add the whole number of rows
            list.add(v);
        }

        return list;
    }
}
